{% set name = "CImg" %}
{% set version = "3.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dtschump/CImg/archive/v.{{ version }}.tar.gz
  sha256: df1378830c8ca9c56b2d46a9eef8ff14daf0808e1a2a765663b47956a3eeda7f

build:
  number: 0

requirements:
  build:
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/CImg.h  # [unix]

about:
  home: http://cimg.eu/
  license: CECILL-2.0
  license_file: Licence_CeCILL_V2-en.txt
  summary: C++ Template Image Processing Toolkit
  description: C++ Template Image Processing Toolkit
  doc_url: http://cimg.eu/reference/index.html
  dev_url: http://cimg.eu/reference/index.html

extra:
  recipe-maintainers:
    - din14970
