{% set name = "CImg" %}
{% set version = "4.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dtschump/CImg/archive/v.{{ version }}.tar.gz
  sha256: bfd21899ab14925fec36b9b398ddfbe34d52f3851a453dabf349857655addc10

build:
  number: 0

requirements:
  build:
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/CImg.h  # [unix]

about:
  home: http://cimg.eu/
  license: CECILL-2.0
  license_file: Licence_CeCILL_V2-en.txt
  summary: C++ Template Image Processing Toolkit
  description: C++ Template Image Processing Toolkit
  doc_url: http://cimg.eu/reference/index.html
  dev_url: http://cimg.eu/reference/index.html

extra:
  recipe-maintainers:
    - din14970
