{% set name = "CImg" %}
{% set version = "4.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dtschump/CImg/archive/v.{{ version }}.tar.gz
  sha256: f9a2916df36617c9d9b7d08d5cad2ec3551e0a60de5277655c238884aea51f44

build:
  number: 0

requirements:
  build:
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/CImg.h  # [unix]

about:
  home: http://cimg.eu/
  license: CECILL-2.0
  license_file: Licence_CeCILL_V2-en.txt
  summary: C++ Template Image Processing Toolkit
  description: C++ Template Image Processing Toolkit
  doc_url: http://cimg.eu/reference/index.html
  dev_url: http://cimg.eu/reference/index.html

extra:
  recipe-maintainers:
    - din14970
