{% set name = "CImg" %}
{% set version = "3.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dtschump/CImg/archive/v.{{ version }}.tar.gz
  sha256: f3102efc0803cb52693b43adf759579feb3dbc018506a8004af5e29b40649ffb

build:
  number: 0

requirements:
  build:
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/CImg.h  # [unix]

about:
  home: http://cimg.eu/
  license: CECILL-2.0
  license_file: Licence_CeCILL_V2-en.txt
  summary: C++ Template Image Processing Toolkit
  description: C++ Template Image Processing Toolkit
  doc_url: http://cimg.eu/reference/index.html
  dev_url: http://cimg.eu/reference/index.html

extra:
  recipe-maintainers:
    - din14970
